persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  type: pvc
  size: 8Gi # example value

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        url: http://loki:3100
        access: proxy
        isDefault: true
